review_version: 3.1
bookname: kaiwaibook
language: ja
booktitle: {name: "We Love 技術同人誌 - 技術書界隈を盛り上げる本 - ", file-as: "kaiwai"}
aut: []
edt: おやかた
pbl: 技術同人誌を盛り上げる会
prt: なし
date: 2020-09-12
history: [["2020-08-27 電子版"]]
rights: (C) 2020 技術書界隈を盛り上げる会
description: 技術同人誌を盛り上げる会の合同誌です
subject: We Love 技術同人誌 - 技術書界隈を盛り上げる本 - 
type: ["技術書", "合同誌", ]
debug: null
stylesheet: ["style.css"]
epubversion: 3
htmlversion: 5
toclevel: 3
secnolevel: 3
toc: true
cover: null
titlefile: chap-title.tex
page_metric: B5
direction: "ltr"
epubmaker:
  htmlext: xhtml
texstyle: ["reviewmacro"]
pdfmaker:
  colophon: true
